version: '3'
services:
  web:
    image: ife
    container_name: ife
    build: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/www
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/logs
